# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: "horace's blog"
title: Hello big, big, BIG World
email: horacetso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wow, this thing actually works. Pretty cool isn't it. I live in _config.yml. 
  Whoever google searches, they will find me here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nodalmarkets.com"
twitter_username: mytwit-dont-have-one
github_username: htso


# Build settings
markdown: kramdown
theme: minima
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
